name: Subir al render con imagen docker

on:
  push:
    branches:
      - desarrollo
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Build Docker image
      run: docker build -t joakod/tpselenium .
      
    - name: Log in to Docker Hub
      run: docker login -u joakod -p ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Push Docker image
      run: docker pull joakod/tpselenium
